#!/bin/sh

set -eu

BUILD_ARCHITECTURES="${BUILD_ARCHITECTURES:-amd64 arm64}"
BUILD_OPERATING_SYSTEMS="${BUILD_OPERATING_SYSTEMS:-darwin linux windows}"
GPG_KEY="${GPG_KEY:-Krakozaure}"
VERSION_FLAG="-X 'main.Version=$(git describe --tags --always --dirty)'"

prog_name="$(basename "$PWD")"
build_dir="./release"

rm -fr -- "${build_dir}"
mkdir -p -- "${build_dir}"

printf '\e[34m-> Building\e[0m\n'
for GOOS in $BUILD_OPERATING_SYSTEMS; do
  for GOARCH in $BUILD_ARCHITECTURES; do
    f="${prog_name}-${GOOS}_${GOARCH}"
    echo " - $f"
    GOARCH="$GOARCH" GOOS="$GOOS" CGO_ENABLED="0" go build -ldflags="$VERSION_FLAG -s -w" -o "${build_dir}/$f"
  done
done

cd -- "${build_dir}"

printf '\e[34m-> Generating checksums & signatures\e[0m\n'
for GOOS in $BUILD_OPERATING_SYSTEMS; do
  for GOARCH in $BUILD_ARCHITECTURES; do
    f="${prog_name}-${GOOS}_${GOARCH}"
    echo " - $f"
    sha256sum "$f" >> "$f.sha256"
    gpg --quiet --yes --default-key "$GPG_KEY" --output "$f.sha256.sig" \
      --detach-sign "$f.sha256"
  done
done
